=== robsman/stardust.ide/modeling/org.eclipse.stardust.modeling.debug/src/org/eclipse/stardust/modeling/debug/interpreter/Metadata.dtd
<?xml encoding="ISO-8859-1"?>
<!ELEMENT DATA_GROUP (DATA_GROUP | DATA | TABLE_DATA)*>
<!ATTLIST DATA_GROUP id CDATA #REQUIRED>
<!ATTLIST DATA_GROUP label CDATA #IMPLIED>
<!ATTLIST DATA_GROUP type CDATA #IMPLIED>
<!ATTLIST DATA_GROUP row CDATA #IMPLIED>
<!ATTLIST DATA_GROUP column CDATA #IMPLIED>
<!ATTLIST DATA_GROUP border (true|false) "false">
<!ATTLIST DATA_GROUP spacken CDATA #IMPLIED>

<!ELEMENT DATA EMPTY>
<!ATTLIST DATA id CDATA #REQUIRED>
<!ATTLIST DATA label CDATA #REQUIRED>
<!ATTLIST DATA type CDATA #REQUIRED>
<!ATTLIST DATA mandatory (true|false) "false">
<!ATTLIST DATA readonly (true|false) "false">
<!ATTLIST DATA length CDATA #IMPLIED>
<!ATTLIST DATA default CDATA #IMPLIED>
<!ATTLIST DATA row CDATA #IMPLIED>
<!ATTLIST DATA column CDATA #IMPLIED>
<!ATTLIST DATA depends_on CDATA #IMPLIED>
<!ATTLIST DATA tooltip CDATA #IMPLIED>

<!ELEMENT TABLE_DATA (COLUMN+)>
<!ATTLIST TABLE_DATA id CDATA #REQUIRED>
<!ATTLIST TABLE_DATA label CDATA #IMPLIED>
<!ATTLIST TABLE_DATA readonly CDATA #IMPLIED>
<!ATTLIST TABLE_DATA row CDATA #IMPLIED>
<!ATTLIST TABLE_DATA column CDATA #IMPLIED>
<!ATTLIST TABLE_DATA tooltip CDATA #IMPLIED>

<!ELEMENT COLUMN EMPTY>
<!ATTLIST COLUMN id CDATA #REQUIRED>
<!ATTLIST COLUMN label CDATA #REQUIRED>
<!ATTLIST COLUMN type CDATA #REQUIRED>
<!ATTLIST COLUMN mandatory (true|false) "false">
<!ATTLIST COLUMN readonly (true|false) "false">
<!ATTLIST COLUMN length CDATA #IMPLIED>
<!ATTLIST COLUMN row CDATA #IMPLIED>
<!ATTLIST COLUMN column CDATA #IMPLIED>
<!ATTLIST COLUMN depends_on CDATA #IMPLIED>
<!ATTLIST COLUMN tooltip CDATA #IMPLIED>

=== robsman/stardust.ide/modeling/org.eclipse.stardust.modeling.debug/src/org/eclipse/stardust/modeling/debug/interpreter/test.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE DATA_GROUP SYSTEM "Metadata.dtd">
<!-- Revision 1.1 data/unknown, docs, xml4j2, -->
<DATA_GROUP id="12" label="SA26">
<DATA id="12" type="integer" label="DACS-ID" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="DACS-ID-lfd.-Nr." mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Satzart" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Satzkennung" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Unsicherheits-KZ" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Dienststelle" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Schalter" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Ausgabedatum" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Beleg-Nr." mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Verkaufsart" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Kz-Buchungsart" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Rechnungsmonat" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Hin/Rück-Kz." mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Gesamterlös" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Erlös je Karte" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Anzahl verk. Karten" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Erwachsene" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Kinder" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Klasse-DB" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Verkaufsanweisung" mandatory="true" readonly="false">
</DATA>
<DATA_GROUP id="12" label="Stammteil Kurs '90">
<DATA_GROUP id="12">
<DATA id="12" type="integer" label="Ausgabestelle" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Ausgabe-Schalter" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Akquirierende Dst." mandatory="true" readonly="true">
</DATA>
<TABLE_DATA id="12" readonly="true">
<COLUMN id="12" type="int" label="Column 1" mandatory="true" readonly="true">
</COLUMN>
<COLUMN id="12" type="int" label="Column 2" mandatory="true" readonly="true">
</COLUMN>
<COLUMN id="12" type="int" label="Column 3" mandatory="true" readonly="true">
</COLUMN>
</TABLE_DATA>
</DATA_GROUP>
<DATA_GROUP id="12">
<DATA id="12" type="integer" label="1. Geltungstag" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Letzter Geltungstag" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Ausgabezeit" mandatory="true" readonly="true">
</DATA>
</DATA_GROUP>
<DATA_GROUP id="12">
<DATA id="12" type="integer" label="Kostenzuschlag DB" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Kostenzuschlag 3te" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Sonstige Einnahmen" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Preisnachlass" mandatory="true" readonly="false">
</DATA>
<DATA id="12" type="integer" label="Fahrgeldanteil 3-te" mandatory="true" readonly="false">
</DATA>
</DATA_GROUP>
</DATA_GROUP>
<DATA_GROUP id="12" label="DB">
<DATA_GROUP id="12" label="Subgroup1">
<DATA id="12" type="integer" label="Label1" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label2" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label3" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label4" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label5" mandatory="true" readonly="true">
</DATA>
</DATA_GROUP>
<DATA_GROUP id="12" label="Subgroup2">
<DATA id="12" type="integer" label="Label1" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label2" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label3" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label4" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label5" mandatory="true" readonly="true">
</DATA>
</DATA_GROUP>
<DATA_GROUP id="12" label="Subgroup2">
<DATA id="12" type="integer" label="Label1" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label2" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label3" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label4" mandatory="true" readonly="true">
</DATA>
<DATA id="12" type="integer" label="Label5" mandatory="true" readonly="true">
</DATA>
</DATA_GROUP>
</DATA_GROUP>
<DATA_GROUP id="12" label="ICE">
</DATA_GROUP>
<DATA_GROUP id="12" label="TCV">
</DATA_GROUP>
<DATA_GROUP id="12" label="Sonstige">
</DATA_GROUP>
</DATA_GROUP>
